version: '3.8'

services:
  ghdb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghdb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1434:1433"
    networks:
      - gh-network
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    entrypoint: /bin/bash -c "/opt/mssql/bin/sqlservr & sleep 30s & /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'yourStrong(!)Password' -i /docker-entrypoint-initdb.d/init.sql"
    restart: always
    
  frontend:
    build:
      context: ./ti-gamerhistory-angular  
      dockerfile: Dockerfile
    container_name: ghAngular
    ports:
      - "8080:4200"
    networks:
      - gh-network

  backend:
    build: 
      context: .
      dockerfile: ti-gamerhistory-asp/Controller/Dockerfile
    container_name: ghApi
    ports:
      - "5037:5037"
    depends_on:
      - ghdb
    networks:
      - gh-network
    environment:
      - ConnectionStrings__db=Server=ghdb;Database=gamer_history_db;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=true
    restart: always

networks:
  gh-network:
    driver: bridge